"""empty message

Revision ID: 14833f175627
Revises: c9406a63f17b
Create Date: 2020-08-24 19:25:40.192768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14833f175627'
down_revision = 'c9406a63f17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('user', sa.Column('address', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
