"""empty message

Revision ID: 368d50ae7948
Revises: 763c4011ccb0
Create Date: 2020-08-27 15:11:21.448462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '368d50ae7948'
down_revision = '763c4011ccb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.drop_column('weibo', 'created_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('created_time', mysql.DATETIME(), nullable=False))
    op.drop_column('weibo', 'create_time')
    # ### end Alembic commands ###
