"""empty message

Revision ID: a88ae948b048
Revises: 14833f175627
Create Date: 2020-08-24 20:58:39.159390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a88ae948b048'
down_revision = '14833f175627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.drop_column('weibo', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('created_date', mysql.DATETIME(), nullable=True))
    op.drop_column('weibo', 'created_time')
    # ### end Alembic commands ###
